name: Generate README After Pages Enabled

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  update-readme-if-pages-enabled:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Check if GitHub Pages is enabled
        id: check-pages
        run: |
          response=$(curl -s -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pages)

          echo "$response" | grep '"status":' > pages_status.json || echo '{}' > pages_status.json
          if grep -q '"status": "built"' pages_status.json; then
            echo "pages_enabled=true" >> $GITHUB_OUTPUT
          else
            echo "pages_enabled=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate README.md (only if Pages enabled)
        if: steps.check-pages.outputs.pages_enabled == 'true'
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          OWNER="${{ github.repository_owner }}"
          sed -e "s|{{REPO_NAME}}|$REPO_NAME|g" \
              -e "s|{{OWNER}}|$OWNER|g" \
              README.template.md > README.md

      - name: Commit and Push Updated README
        if: steps.check-pages.outputs.pages_enabled == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "Auto-generate README.md after Pages enabled" || echo "No changes to commit"
          git push
